baseURL = "https://katabex.com/"
languageCode = "en-us"
title = "Katabex"
theme="archie"
copyright = "© Katabex"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "katabex"

[pagination]
  pagerSize = 3 # articles per page

[params]
    mode="toggle" # color-mode → light,dark,toggle or auto
    useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
#    subtitle = "Yet another personal site"
#   mathjax = true # enable MathJax support
    mathjax = false # enable MathJax support
    katex = true # enable KaTeX support
    favicon ="/favicon.ico"
#    customcss= ["css/main.css"]

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/katabex"

#[[params.social]]
#name = "Twitter"
#icon = "twitter"
#url = "https://x.com/katabex"

#[[params.social]]
#name = "GitLab"
#icon = "gitlab"
#url = "https://gitlab.com/athul/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[caches]
  [caches.images]
    dir = ':cacheDir/images'
